### ISSUE TITLE
releaseOnGitHub array index out of bounds

### ISSUE THREAD

**Issue by eparejatobes** [ohnosequences/nice-sbt-settings#53]
trace:

```
[info] Using release notes from the [notes/0.11.0.markdown] file
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.kohsuke.github.GitHub.getRepository(GitHub.java:289)
	at ohnosequences.sbt.SbtGithubReleasePlugin$$anonfun$projectSettings$11.apply(SbtGithubReleasePlugin.scala:92)
	at ohnosequences.sbt.SbtGithubReleasePlugin$$anonfun$projectSettings$11.apply(SbtGithubReleasePlugin.scala:73)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by laughedelic** [comment]
This is https://github.com/ohnosequences/sbt-github-release/pull/6. I'll release it and update here. Check the `repo` setting, it's about project (normalized) name not corresponding to the github repo name
